export const TAKE_FROM_STORAGE ='TAKE_FROM_STORAGE';
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const FILTER = 'FILTER';

export const ADD_CONTACT_REQUEST_START = "ADD_CONTACT_REQUEST_START";
export const ADD_CONTACT_REQUEST_SUCCESS = 'ADD_CONTACT_REQUEST_SUCCESS';
export const DELETE_CONTACT_REQUEST_START = 'DELETE_CONTACT_REQUEST_START';
export const DELETE_CONTACT_REQUEST_SUCCESS = 'DELETE_CONTACT_REQUEST_SUCCESS';

export const ADD_CONTACT_REQUEST_ERROR = 'ADD_CONTACT_REQUEST_ERROR';
export const DELETE_CONTACT_REQUEST_ERROR = 'DELETE_CONTACT_REQUEST_ERROR';
export const ERROR_RESET = 'ERROR_RESET';

export const LOAD_ERROR = "LOAD_ERROR";
export const LOAD_REQUEST_START = "LOAD_REQUEST_START";
export const LOAD_REQUEST_SUCCESS = "LOAD_REQUEST_SUCCESS"